---
# https://github.com/NVIDIA/nvidia-docker
- name: Setting up for the NVIDIA Container toolkit
  block:
    - name: Collect distribution detail
      set_fact:
        distribution: "{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}"
      when: ansible_os_family != "RedHat"

    - name: Add repository
      get_url:
        url: "https://nvidia.github.io/libnvidia-container/rhel9.0/libnvidia-container.repo"
        dest: /etc/yum.repos.d/nvidia-container-toolkit.repo
        mode: '0644'
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '9'

    - name: Add repository
      get_url:
        url: "https://nvidia.github.io/nvidia-docker/centos8/nvidia-docker.repo"
        dest: /etc/yum.repos.d/nvidia-container.repo
        mode: '0644'
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8'

- name: install the latest version of the NVIDIA Container Toolkit
  yum:
    name: nvidia-container-toolkit
    state: latest
    update_cache: true
  notify:
    - restart docker
  when: install_nvidia_container | bool
